### ISSUE TITLE
How to change the DNS Name Pi gets

### ISSUE THREAD

**Issue by varungujjar** [stonehippo/tiny-mdns-proxy#1]
So basically i managed to install this successfully.. this is amazing..  however my raspberry pi gets some random DNS name DESKTOP-VQTJDED  is there a way to change that ..?

**Comment by stonehippo** [comment]
> So basically i managed to install this successfully.. this is amazing..  however my raspberry pi gets some random DNS name DESKTOP-VQTJDED  is there a way to change that ..? 

Hi @varungujjar sorry, I didn't see this issue before. A couple of things:

- First, if you're still using the proxy, you should pull the latest, as I recently made some fixes to the returned DNS record format. 
- Second, the mDNS record for most devices will be _hostname_.local. If you need to change the hostname of your RPi, you can do that via `raspi-config`

In any case, if you are using pm2 to daemonize the proxy, you can take a look at the running log with the command `pm2 monit`. That should show you all of the queries and responses.
